In [37]:
import pandas as pd

# Load data from CSV files
investments_df = pd.read_csv('data/investments.csv')
applications_df = pd.read_csv('data/applications.csv')
returns_df = pd.read_csv('data/returns.csv')

In [38]:
# Initialize an empty DataFrame for the profit history log
profit_history_df = pd.DataFrame(columns=['date', 'investment_name', 'total_return', 'applications_after_last_return', 'profit'])

print(applications_df)
print(returns_df)
print(profit_history_df)

   id  investment_name  application_value application_date
0   1           Stocks               2000       2022-01-05
1   2  Treasury Direct               3000       2022-02-20
2   3      Real Estate               2500       2022-03-15
3   4           Stocks               4000       2022-04-01
4   5  Treasury Direct               1500       2022-05-10
5   6      Real Estate               6000       2022-06-15
6   7           Stocks               3500       2022-07-02
7   8  Treasury Direct               4500       2022-08-18
8   9   Cryptocurrency               2000       2022-09-22
9  10      Real Estate               3000       2022-10-12
    id  investment_name  total_amount date_received
0    1           Stocks          1050    2022-01-10
1    2  Treasury Direct          1100    2022-02-25
2    3  Savings Account          1130    2022-03-20
3    4           Stocks          1210    2022-04-05
4    5  Treasury Direct          1330    2022-05-01
5    6           Stocks          2050    2022-01-15
6    7  Treasury Direct          3200    2022-02-28
7    8      Real Estate          4000    2022-03-25
8    9           Stocks          5000    2022-04-10
9   10  Treasury Direct          1650    2022-05-15
10  11      Real Estate          7000    2022-06-20
11  12           Stocks          4000    2022-07-10
12  13  Treasury Direct          5000    2022-08-25
13  14   Cryptocurrency          2300    2022-09-30
14  15      Real Estate          3300    2022-10-20
15  16           Stocks          1400    2022-04-15
16  17  Treasury Direct          1550    2022-05-20
17  18  Savings Account          1630    2022-06-05
18  19           Stocks          1750    2022-07-15
19  20  Treasury Direct          1930    2022-08-01
Empty DataFrame
Columns: [date, investment_name, total_return, applications_after_last_return, profit]
Index: []

In [39]:
# Calculate profit history for each investment
for index, return_row in returns_df.iterrows():
    investment_name = return_row['investment_name']
    date = return_row['date_received']
    total_return = return_row['total_amount']

    last_return = returns_df[(returns_df['investment_name'] == investment_name) & (returns_df['date_received'] < date)].sort_values(by=['date_received'], ascending=False)


    # Calculate the profit percentage
    if last_return.empty:
        last_return_value = investments_df[(investments_df['investment_name'] == investment_name)].iloc[0]['investment_value']
        last_return_date = investments_df[(investments_df['investment_name'] == investment_name)].iloc[0]['investment_date']
    else:
        last_return_value = last_return.iloc[0]['total_amount']
        last_return_date = last_return.iloc[0]['date_received']

    # Filter applications made after the last return date
    filtered_applications = applications_df[(applications_df['investment_name'] == investment_name) & (applications_df['application_date'] > last_return_date) & (applications_df['application_date'] < date)]

    applications_after_last_return = filtered_applications['application_value'].sum()

    profit_percentage = ((total_return + applications_after_last_return - last_return_value) / last_return_value) * 100

    # Append to profit history log
    profit_history_df = pd.concat([pd.DataFrame({
        'date': [date],
        'investment_name': [investment_name],
        'total_return': [total_return],
        'last_return_value': [last_return_value],
        'applications_after_last_return': [applications_after_last_return],
        'profit_percentage': [profit_percentage]
    }), profit_history_df], ignore_index=True)

In [40]:
profit_history_df

,date,investment_name,total_return,last_return_value,applications_after_last_return,profit_percentage,profit
0,2022-08-01,Treasury Direct,1930,1550.0,0,24.516129,NaN
1,2022-07-15,Stocks,1750,4000.0,0,-56.250000,NaN
2,2022-06-05,Savings Account,1630,1130.0,0,44.247788,NaN
3,2022-05-20,Treasury Direct,1550,1650.0,0,-6.060606,NaN
4,2022-04-15,Stocks,1400,5000.0,0,-72.000000,NaN
5,2022-10-20,Real Estate,3300,7000.0,3000,-10.000000,NaN
6,2022-09-30,Cryptocurrency,2300,3000.0,2000,43.333333,NaN
7,2022-08-25,Treasury Direct,5000,1930.0,4500,392.227979,NaN
8,2022-07-10,Stocks,4000,1400.0,3500,435.714286,NaN
9,2022-06-20,Real Estate,7000,4000.0,6000,225.000000,NaN
10,2022-05-15,Treasury Direct,1650,1330.0,1500,136.842105,NaN
11,2022-04-10,Stocks,5000,1210.0,0,313.223140,NaN
12,2022-03-25,Real Estate,4000,8000.0,0,-50.000000,NaN
13,2022-02-28,Treasury Direct,3200,1100.0,0,190.909091,NaN
14,2022-01-15,Stocks,2050,1050.0,0,95.238095,NaN
15,2022-05-01,Treasury Direct,1330,3200.0,0,-58.437500,NaN
16,2022-04-05,Stocks,1210,2050.0,4000,154.146341,NaN
17,2022-03-20,Savings Account,1130,2000.0,0,-43.500000,NaN
18,2022-02-25,Treasury Direct,1100,5000.0,3000,-18.000000,NaN
19,2022-01-10,Stocks,1050,1000.0,2000,205.000000,NaN